version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
        update-types:
          - "major"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
          - "globals"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
